{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import cv2\n",
    "import pytesseract as pt\n",
    "import pickle\n",
    "import os\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "tfidf = TfidfVectorizer()\n",
    "\n",
    "css = \"\"\"\n",
    "<style>\n",
    "@keyframes move {\n",
    "    100% {\n",
    "        transform: translate3d(0, 0, 1px) rotate(360deg);\n",
    "    }\n",
    "}\n",
    "\n",
    ".background {\n",
    "    position: fixed;\n",
    "    width: 100vw;\n",
    "    height: 100vh;\n",
    "    top: 0;\n",
    "    left: 0;\n",
    "    background: #fffce6;\n",
    "    overflow: hidden;\n",
    "}\n",
    "\n",
    ".background span {\n",
    "    width: 15vmin;\n",
    "    height: 15vmin;\n",
    "    border-radius: 15vmin;\n",
    "    backface-visibility: hidden;\n",
    "    position: absolute;\n",
    "    animation: move;\n",
    "    animation-duration: 25s;\n",
    "    animation-timing-function: linear;\n",
    "    animation-iteration-count: infinite;\n",
    "}\n",
    "\n",
    ".background span:nth-child(0) {\n",
    "    color: #e7f0f4;\n",
    "    top: 56%;\n",
    "    left: 10%;\n",
    "    animation-duration: 76s;\n",
    "    animation-delay: -102s;\n",
    "    transform-origin: -12vw 6vh;\n",
    "    box-shadow: -30vmin 0 4.2850209678796904vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(1) {\n",
    "    color: #e7f0f4;\n",
    "    top: 24%;\n",
    "    left: 96%;\n",
    "    animation-duration: 152s;\n",
    "    animation-delay: -156s;\n",
    "    transform-origin: 3vw 8vh;\n",
    "    box-shadow: 30vmin 0 4.001761009505196vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(2) {\n",
    "    color: #aec6cf;\n",
    "    top: 23%;\n",
    "    left: 96%;\n",
    "    animation-duration: 22s;\n",
    "    animation-delay: -244s;\n",
    "    transform-origin: -13vw 1vh;\n",
    "    box-shadow: 30vmin 0 3.874379473160472vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(3) {\n",
    "    color: #e7f0f4;\n",
    "    top: 99%;\n",
    "    left: 83%;\n",
    "    animation-duration: 246s;\n",
    "    animation-delay: -38s;\n",
    "    transform-origin: 2vw 13vh;\n",
    "    box-shadow: 30vmin 0 4.3384802129291105vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(4) {\n",
    "    color: #e7f0f4;\n",
    "    top: 54%;\n",
    "    left: 13%;\n",
    "    animation-duration: 134s;\n",
    "    animation-delay: -115s;\n",
    "    transform-origin: -11vw -21vh;\n",
    "    box-shadow: -30vmin 0 3.9260329587822396vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(5) {\n",
    "    color: #e7f0f4;\n",
    "    top: 8%;\n",
    "    left: 73%;\n",
    "    animation-duration: 216s;\n",
    "    animation-delay: -200s;\n",
    "    transform-origin: -19vw -11vh;\n",
    "    box-shadow: 30vmin 0 3.889693724619526vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(6) {\n",
    "    color: #e7f0f4;\n",
    "    top: 87%;\n",
    "    left: 79%;\n",
    "    animation-duration: 181s;\n",
    "    animation-delay: -63s;\n",
    "    transform-origin: -8vw -16vh;\n",
    "    box-shadow: 30vmin 0 4.198411946293855vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(7) {\n",
    "    color: #e7f0f4;\n",
    "    top: 99%;\n",
    "    left: 35%;\n",
    "    animation-duration: 189s;\n",
    "    animation-delay: -182s;\n",
    "    transform-origin: -12vw 11vh;\n",
    "    box-shadow: 30vmin 0 3.957988827082369vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(8) {\n",
    "    color: #aec6cf;\n",
    "    top: 9%;\n",
    "    left: 4%;\n",
    "    animation-duration: 41s;\n",
    "    animation-delay: -206s;\n",
    "    transform-origin: 1vw 7vh;\n",
    "    box-shadow: -30vmin 0 4.6830992652098695vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(9) {\n",
    "    color: #e7f0f4;\n",
    "    top: 56%;\n",
    "    left: 81%;\n",
    "    animation-duration: 204s;\n",
    "    animation-delay: -59s;\n",
    "    transform-origin: -2vw 21vh;\n",
    "    box-shadow: 30vmin 0 4.362591393251875vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(10) {\n",
    "    color: #e7f0f4;\n",
    "    top: 51%;\n",
    "    left: 95%;\n",
    "    animation-duration: 106s;\n",
    "    animation-delay: -142s;\n",
    "    transform-origin: 20vw -10vh;\n",
    "    box-shadow: -30vmin 0 4.30464603282698vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(11) {\n",
    "    color: #e7f0f4;\n",
    "    top: 5%;\n",
    "    left: 56%;\n",
    "    animation-duration: 158s;\n",
    "    animation-delay: -39s;\n",
    "    transform-origin: 13vw -18vh;\n",
    "    box-shadow: -30vmin 0 4.49764479881048vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(12) {\n",
    "    color: #aec6cf;\n",
    "    top: 27%;\n",
    "    left: 82%;\n",
    "    animation-duration: 121s;\n",
    "    animation-delay: -144s;\n",
    "    transform-origin: 1vw -12vh;\n",
    "    box-shadow: 30vmin 0 4.588205242391293vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(13) {\n",
    "    color: #aec6cf;\n",
    "    top: 9%;\n",
    "    left: 85%;\n",
    "    animation-duration: 107s;\n",
    "    animation-delay: -121s;\n",
    "    transform-origin: -17vw -4vh;\n",
    "    box-shadow: -30vmin 0 3.993678747491651vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(14) {\n",
    "    color: #e7f0f4;\n",
    "    top: 69%;\n",
    "    left: 74%;\n",
    "    animation-duration: 240s;\n",
    "    animation-delay: -162s;\n",
    "    transform-origin: 23vw -8vh;\n",
    "    box-shadow: 30vmin 0 3.7523169104251917vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(15) {\n",
    "    color: #aec6cf;\n",
    "    top: 97%;\n",
    "    left: 31%;\n",
    "    animation-duration: 83s;\n",
    "    animation-delay: -207s;\n",
    "    transform-origin: -1vw -21vh;\n",
    "    box-shadow: -30vmin 0 4.1247653016130785vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(16) {\n",
    "    color: #e7f0f4;\n",
    "    top: 87%;\n",
    "    left: 45%;\n",
    "    animation-duration: 116s;\n",
    "    animation-delay: -87s;\n",
    "    transform-origin: -19vw -2vh;\n",
    "    box-shadow: 30vmin 0 4.635123079514468vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(17) {\n",
    "    color: #aec6cf;\n",
    "    top: 43%;\n",
    "    left: 77%;\n",
    "    animation-duration: 239s;\n",
    "    animation-delay: -90s;\n",
    "    transform-origin: -1vw -20vh;\n",
    "    box-shadow: -30vmin 0 4.715496254559995vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(18) {\n",
    "    color: #aec6cf;\n",
    "    top: 7%;\n",
    "    left: 60%;\n",
    "    animation-duration: 61s;\n",
    "    animation-delay: -139s;\n",
    "    transform-origin: 14vw 7vh;\n",
    "    box-shadow: -30vmin 0 4.02343739770485vmin currentColor;\n",
    "}\n",
    ".background span:nth-child(19) {\n",
    "    color: #aec6cf;\n",
    "    top: 35%;\n",
    "    left: 72%;\n",
    "    animation-duration: 51s;\n",
    "    animation-delay: -129s;\n",
    "    transform-origin: -2vw -14vh;\n",
    "    box-shadow: 30vmin 0 4.2584078024709235vmin currentColor;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "html = \"\"\"\n",
    "<div class=\"background\">\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "   <span></span>\n",
    "</div>\n",
    "\"\"\"\n",
    "\n",
    "non_animated_css = \"\"\"\n",
    "<style>\n",
    "[data-testid=\"stSidebar\"] {\n",
    "    background-color: #6E8091;\n",
    "    opacity: 1;\n",
    "    position: fixed;\n",
    "    width: 20%;\n",
    "    height: 100vh;\n",
    "    top: 0;\n",
    "    left: 0;\n",
    "    overflow: auto;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "header_css = \"\"\"\n",
    "<style>\n",
    "[class=\"st-emotion-cache-1avcm0n ezrtsby2\"] {\n",
    "    background-color: #95B5CA;\n",
    "    opacity: 1;\n",
    "    position: absolute;\n",
    "    width: 100%;\n",
    "    height: 7vh;\n",
    "    top: 0;\n",
    "    left: 0;\n",
    "    overflow: auto;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "st.markdown(css, unsafe_allow_html=True)\n",
    "st.markdown(html, unsafe_allow_html=True)\n",
    "st.markdown(non_animated_css, unsafe_allow_html=True)\n",
    "st.markdown(header_css, unsafe_allow_html=True)\n",
    "\n",
    "def page1():\n",
    "    st.markdown('<h2 style=\"color: black; text-align: center; font-family: Georgia, serif;\"><b>Real vs Satirical News Detector</b></h2>', unsafe_allow_html=True)\n",
    "    st.write(\"\\n\\n\\n\")\n",
    "    st.markdown('''<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>In this day and age where fake news spreads faster than genuine information, satirical news can be a double-edged sword.\n",
    "    Providing both humour and critical perspectives, satirical news serves as both a source of entertainment and social commentary.\n",
    "    However, its capability to be confused with genuine information, because of misinformation, similarity of medium and style,\n",
    "    and presence of confirmation bias leading to reduced trust in media and increased discourse, highlights the importance of\n",
    "    critical thinking and media literacy while drawing in with such content. The goal of this project is to distinguish\n",
    "    Satirical News from Real News to combat this critical and relevant issue.</b></p>''', unsafe_allow_html=True)\n",
    "    st.write(\"\\n\\n\")\n",
    "    st.markdown('''<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>To solve this issue, we have created an AI model using various Machine Learning algorithms like KNN and Naive Bayes\n",
    "    and created a user-friendly interface to distinguish between Real and Satirical News.</b></p>''', unsafe_allow_html=True)\n",
    "    st.write(\"\\n\\n\")\n",
    "    st.markdown('''<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>You can input either text of the article, or a screenshot of the article. It also has a choice over whether the user\n",
    "    wants to upload the heading of the article, the body of the article, or the entire combined article. The model runs and gives\n",
    "    output as either Satirical News or Real News.</b></p>''', unsafe_allow_html=True)\n",
    "\n",
    "def page2():\n",
    "    st.markdown('<h2 style=\"color: black; text-align: center; font-family: Georgia, serif;\"><b>Use Text</b></h2>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>1. Heading of article</b></p>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>2. Content of article</b></p>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>3. Whole article</b></p>', unsafe_allow_html=True)\n",
    "    st.write(\"\\n\\n\")\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Please enter option of your choice here</b></p>', unsafe_allow_html=True)\n",
    "    choice = st.number_input(\" \",min_value=1,max_value=3,step=1)\n",
    "    st.write(\"\\n\")\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Enter text here</b></p>', unsafe_allow_html=True)\n",
    "    text = st.text_input(\" \")\n",
    "    st.write(\"\\n\")\n",
    "    if choice==1:\n",
    "        #inputData = preprocess(text)\n",
    "        with open(\"tfidfHeading\", 'rb') as file:\n",
    "            tfidf_model = pickle.load(file)\n",
    "        inputData = tfidf_model.transform([text])\n",
    "        with open(\"nbHeading\", 'rb') as file:\n",
    "            loaded_model = pickle.load(file)\n",
    "        output=loaded_model.predict(inputData)\n",
    "        if output[0]==0:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "        elif output[0]==1:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "    elif choice==2:\n",
    "        #inputData = preprocess(text)\n",
    "        with open(\"tfidfText\", 'rb') as file:\n",
    "            tfidf_model = pickle.load(file)\n",
    "        inputData = tfidf_model.transform([text])\n",
    "        with open(\"nbText\", 'rb') as file:\n",
    "            loaded_model = pickle.load(file)\n",
    "        output=loaded_model.predict(inputData)\n",
    "        if output[0]==0:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "        elif output[0]==1:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "    else:\n",
    "        #inputData = preprocess(text)\n",
    "        with open(\"tfidfCombined\", 'rb') as file:\n",
    "            tfidf_model = pickle.load(file)\n",
    "        inputData = tfidf_model.transform([text])\n",
    "        with open(\"knnCombined\", 'rb') as file:\n",
    "            loaded_model = pickle.load(file)\n",
    "        output=loaded_model.predict(inputData)\n",
    "        if output[0]==0:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "        elif output[0]==1:\n",
    "            st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "\n",
    "def page3():\n",
    "    st.markdown('<h2 style=\"color: black; text-align: center; font-family: Georgia, serif;\"><b>Use Image</b></h2>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>1. Heading of article</b></p>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>2. Content of article</b></p>', unsafe_allow_html=True)\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>3. Whole article</b></p>', unsafe_allow_html=True)\n",
    "    st.write(\"\\n\")\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Please enter option of your choice here</b></p>', unsafe_allow_html=True)\n",
    "    choice = st.number_input(\" \",min_value=1,max_value=3,step=1)\n",
    "    st.write(\"\\n\")\n",
    "    st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Please upload an image in .jpg, .jpeg or .png format</b></p>', unsafe_allow_html=True)\n",
    "    uploaded_file = st.file_uploader(\" \", type=[\"jpg\", \"jpeg\", \"png\"])\n",
    "    st.write(\"\\n\")\n",
    "    if uploaded_file is not None:\n",
    "        st.markdown('<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Uploaded Image:</b></p>', unsafe_allow_html=True)\n",
    "        st.image(uploaded_file, width=200)\n",
    "        upload_dir = \"uploads\"\n",
    "        if not os.path.exists(upload_dir):\n",
    "            os.makedirs(upload_dir)\n",
    "        file_path = os.path.join(upload_dir, uploaded_file.name)\n",
    "        with open(file_path, \"wb\") as f:\n",
    "            f.write(uploaded_file.getbuffer())\n",
    "        image_path = os.path.join(\"uploads\", uploaded_file.name)\n",
    "        image = cv2.imread(file_path)\n",
    "        textFromImage = pt.image_to_string(image)\n",
    "        textFromImage = str(textFromImage)\n",
    "        if choice==1:\n",
    "            st.markdown(f'<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Text extracted from image: <h6 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">{textFromImage}</h6></b></p>', unsafe_allow_html=True)\n",
    "            with open(\"tfidfHeading\", 'rb') as file:\n",
    "                tfidf_model = pickle.load(file)\n",
    "            inputData = tfidf_model.transform([textFromImage])\n",
    "            with open(\"nbHeading\", 'rb') as file:\n",
    "                loaded_model = pickle.load(file)\n",
    "            output=loaded_model.predict(inputData)\n",
    "            if output[0]==0:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "            elif output[0]==1:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "        elif choice==2:\n",
    "            st.markdown(f'<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Text extracted from image: <h6 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">{textFromImage}</h6></b></p>', unsafe_allow_html=True)\n",
    "            with open(\"tfidfText\", 'rb') as file:\n",
    "                tfidf_model = pickle.load(file)\n",
    "            inputData = tfidf_model.transform([textFromImage])\n",
    "            with open(\"nbText\", 'rb') as file:\n",
    "                loaded_model = pickle.load(file)\n",
    "            output=loaded_model.predict(inputData)\n",
    "            if output[0]==0:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "            elif output[0]==1:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "        else:\n",
    "            st.markdown(f'<p style=\"color: black; text-align: justify; font-family: Georgia, serif;\"><b>Text extracted from image: <h6 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">{textFromImage}</h6></b></p>', unsafe_allow_html=True)\n",
    "            with open(\"tfidfCombined\", 'rb') as file:\n",
    "                tfidf_model = pickle.load(file)\n",
    "            inputData = tfidf_model.transform([textFromImage])\n",
    "            with open(\"knnCombined\", 'rb') as file:\n",
    "                loaded_model = pickle.load(file)\n",
    "            output=loaded_model.predict(inputData)\n",
    "            if output[0]==0:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Satirical News</h5>', unsafe_allow_html=True)\n",
    "            elif output[0]==1:\n",
    "                st.markdown(f'<h5 style=\"color: black; text-align: justify; font-family: Georgia, serif;\">Result: Real News</h5>', unsafe_allow_html=True)\n",
    "\n",
    "PAGES = {\"About Us...\": page1, \"Use Text\": page2, \"Use Image\": page3}\n",
    "menu_selection = st.sidebar.selectbox('Go to', list(PAGES.keys()))\n",
    "page = PAGES[menu_selection]\n",
    "page()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
